[theme]
base = "dark"
primaryColor = "#6EA8D7"
backgroundColor = "#0C0D0F"
secondaryBackgroundColor = "#161719"
textColor = "#E7E8EA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
